### ISSUE TITLE
fix meme command

### ISSUE THREAD

**Issue by Makiyu-py** [Makiyu-py/KIGM-Discord-Bot#2]
As of Late December 2020, **we have shut down the meme command** due to issues regarding the module that we are using for getting images from Reddit, `asyncpraw`. From our best guess, we think that our issue here is coming from the fact that we can't really, close our session after the command has completed. 

**We are very sorry and hope that we may fix this issue immediately.** For questions, just ask us here, on this thread.

**Comment by ghost** [comment]
why don't you use another library then?

**Comment by Makiyu-py** [comment]
> why don't you use another library then?

like what?

**Comment by Makiyu-py** [comment]
**UPDATE FEBUARY 2021:**

meme command now *fixed* on commit 6ae43c7
